project_id = "iwusumqwyzezjrfbpkiz"

[functions.create-partner]
verify_jwt = false

[functions.retell-webhook]
verify_jwt = false

[functions.setup-retell]
verify_jwt = false

[functions.get-intake-phone]
verify_jwt = false

[functions.manage-user]
verify_jwt = false